package com.biosimilarity.validation.model.trace.Absyn; // Java Package generated by the BNF Converter.

public abstract class ValueExpr implements java.io.Serializable {
  public abstract <R,A> R accept(ValueExpr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.validation.model.trace.Absyn.Numeric p, A arg);

  }

}
