package com.biosimilarity.validation.model.trace.Absyn; // Java Package generated by the BNF Converter.

public abstract class VariableExpr implements java.io.Serializable {
  public abstract <R,A> R accept(VariableExpr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.validation.model.trace.Absyn.Transcription p, A arg);
    public R visit(com.biosimilarity.validation.model.trace.Absyn.AtomLiteral p, A arg);

  }

}
