module Abstrace where

-- Haskell module generated by the BNF converter

newtype Ident = Ident String deriving (Eq,Ord,Show)
data Expression =
   Sequence Expression Expression
 | Application Expression Expression
 | Mention VariableExpr
 | Value ValueExpr
 | Abstraction [VariableExpr] Expression
 | Stipulation VariableExpr Expression
  deriving (Eq,Ord,Show)

data VariableExpr =
   Transcription Expression
 | AtomLiteral Ident
  deriving (Eq,Ord,Show)

data ValueExpr =
   Numeric Integer
  deriving (Eq,Ord,Show)

