{-# OPTIONS -fno-warn-incomplete-patterns #-}
module Printtrace where

-- pretty-printer generated by the BNF converter

import Abstrace
import Char

-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: [a] -> Doc
  prtList = concatD . map (prt 0)

instance Print a => Print [a] where
  prt _ = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString i)



instance Print Expression where
  prt i e = case e of
   Sequence expression0 expression -> prPrec i 0 (concatD [prt 0 expression0 , prt 1 expression])
   Application expression0 expression -> prPrec i 1 (concatD [prt 1 expression0 , prt 2 expression])
   Mention variableexpr -> prPrec i 2 (concatD [prt 0 variableexpr])
   Value valueexpr -> prPrec i 2 (concatD [prt 0 valueexpr])
   Abstraction variableexprs expression -> prPrec i 2 (concatD [doc (showString "(") , prt 0 variableexprs , doc (showString ")") , doc (showString "=>") , prt 2 expression])
   Stipulation variableexpr expression -> prPrec i 2 (concatD [doc (showString "val") , prt 0 variableexpr , doc (showString "=") , prt 2 expression])


instance Print VariableExpr where
  prt i e = case e of
   Transcription expression -> prPrec i 0 (concatD [doc (showString "@") , doc (showString "<") , prt 1 expression , doc (showString ">")])
   AtomLiteral id -> prPrec i 0 (concatD [prt 0 id])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print ValueExpr where
  prt i e = case e of
   Numeric n -> prPrec i 0 (concatD [prt 0 n])



